# Generated by Django 5.1.2 on 2024-10-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_alter_author_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.CharField(default='cheahhonyuen@gmail.com', max_length=50, unique=True),
        ),
    ]
