# Generated by Django 5.1.2 on 2024-10-11 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0004_profile_country_profile_image_url_profile_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='quote',
        ),
    ]
