# Generated by Django 5.1.2 on 2024-10-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0005_remove_profile_country_remove_profile_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='quote',
            field=models.TextField(blank=True, null=True),
        ),
    ]
