# Generated by Django 5.1.2 on 2024-10-11 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
