# Generated by Django 5.1.2 on 2024-10-12 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_author_email_author_image_url'),
        ('courses', '0003_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='authors.author'),
        ),
    ]
